# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-slim

# Install Asymptote for geometric rendering
RUN apt-get update && \
    apt-get install -y --no-install-recommends asymptote && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy package files and TypeScript configuration
COPY package*.json tsconfig.json ./

# Install dependencies without running lifecycle scripts
RUN npm install --ignore-scripts

# Copy source files and build artifacts
COPY . .

# Build the project
RUN npm run build

# Default command to start the MCP server
CMD ["node", "dist/cli.js"]
